name: random_name_generator
description: Dart package for the generation of Random Names, based on most common names
version: 1.0.0
homepage: https://github.com/poqueque/random_name_generator

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
